name: kanji_app
version: 0.1.0

environment:
  sdk: 3.9.0-138.0.dev
  flutter: 3.33.0-1.0.pre.122

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^15.1.2
  leancode_hooks: ^0.1.1
  logging: ^1.3.0
  provider: ^6.1.5
  super_sliver_list: ^0.4.1

dev_dependencies:
  arb_utils: ^0.8.3
  build_runner: ^2.4.15
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  go_router_builder: ^2.9.0
  leancode_lint: ^16.0.0

dependency_overrides:
  archive: ^4.0.7
  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/kanji.jsonl.xz

  fonts:
    - family: Material Symbols Rounded
      fonts:
        - asset: assets/fonts/MaterialSymbolsRounded.ttf
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/RobotoFlex.ttf
    - family: KleeOne
      fonts:
        - asset: assets/fonts/KleeOne.ttf
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP.ttf
