name: kanji_app
version: 0.1.0

environment:
  sdk: 3.8.0-265.0.dev
  flutter: 3.32.0-1.0.pre.73

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.2
  go_router: ^14.8.1
  leancode_hooks: ^0.1.1
  provider: ^6.1.4

dev_dependencies:
  build_runner: ^2.4.15
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  go_router_builder: ^2.8.2
  leancode_lint: ^15.1.0

flutter:
  uses-material-design: true

  assets:
    - kanji_data/1/
    - kanji_data/2/
    - kanji_data/3/
    - kanji_data/4/

  fonts:
    - family: Material Symbols Rounded
      fonts:
        - asset: assets/fonts/MaterialSymbolsRounded.ttf
