name: kanji_app
version: 0.1.0
publish_to: none

environment:
  sdk: 3.11.0-113.0.dev
  flutter: 3.38.0-1.0.pre-474

dependencies:
  archive: ^4.0.7
  cached_query_flutter: ^3.0.3
  cached_storage: ^3.0.3
  collection: ^1.19.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  go_router: ^17.0.0
  kana_kit: ^2.1.1
  leancode_hooks: ^0.1.2
  logging: ^1.3.0
  material_shapes:
    git: https://github.com/ksokolovskyi/material_shapes
  meta: ^1.17.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5+1
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.1+2
  svg_path_parser: ^1.1.2
  url_launcher: ^6.3.2
  xml: ^6.6.1

dev_dependencies:
  arb_utils: ^0.9.0
  build_runner: ^2.10.1
  characters: ^1.4.0
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  excel:
    git: https://github.com/justkawal/excel
  file: ^7.0.1
  go_router_builder: ^4.1.1
  leancode_lint: ^20.0.0-dev.5

dependency_overrides:
  archive: ^4.0.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/kanji.jsonl.xz
    - assets/radicals.jsonl.xz

  fonts:
    - family: Material Symbols Rounded
      fonts:
        - asset: assets/fonts/MaterialSymbolsRounded.ttf
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/RobotoFlex.ttf
    - family: KleeOne
      fonts:
        - asset: assets/fonts/KleeOne.ttf
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP.ttf
    - family: Yu Kyokasho
      fonts:
        - asset: assets/fonts/Kyokasho.ttc
