name: kanji_app
version: 0.1.0

environment:
  sdk: 3.8.0-265.0.dev
  flutter: 3.32.0-1.0.pre.73

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  provider: ^6.1.4

dev_dependencies:
  build_runner: ^2.4.15
  custom_adaptive_scaffold: ^2.0.1
  go_router_builder: ^2.8.2
  leancode_lint: ^15.1.0

flutter:
  uses-material-design: true
